from __future__ import annotations

from contextlib import AbstractContextManager
from typing import TYPE_CHECKING, Callable, Protocol

if TYPE_CHECKING:
    from .config import Settings
    from .security import Principal


class KnowledgePort(Protocol):
    def ensure_resources(self) -> None: ...
    def refresh(self) -> dict: ...
    def status(self) -> dict: ...
    def search(self, question: str, scope_key: str) -> list[dict]: ...


class OperationStorePort(Protocol):
    def ensure_ready(self) -> None: ...
    def read(self, principal: Principal, operation_id: str) -> dict: ...
    def list(self, principal: Principal) -> list[dict]: ...
    def propose(self, principal: Principal, scope_key: str, tool_name: str, request: dict, preview: dict) -> dict: ...
    def approve(self, principal: Principal, operation_id: str, plan_hash: str, *, confirmation_phrase: str | None = None) -> dict: ...
    def execute(self, principal: Principal, operation_id: str, callback: Callable[[dict], dict]) -> dict: ...
    def observe(self, principal: Principal, operation_id: str, callback: Callable[[dict], dict]) -> dict: ...
    def continue_operation(self, principal: Principal, operation_id: str, plan_hash: str, observation_hash: str,
                           callback: Callable[[dict], dict]) -> dict: ...
    def cancel(self, principal: Principal, operation_id: str) -> dict: ...


class FactoryToolPort(Protocol):
    def descriptors(self) -> list[dict]: ...
    def execute(self, name: str, arguments: dict) -> dict: ...
    def prepare_settings(self, arguments: dict) -> dict: ...
    def prepare_skill(self, name: str, arguments: dict) -> dict: ...
    def execute_operation(self, record: dict) -> dict: ...
    def status_operation(self, record: dict) -> dict: ...
    def continue_operation(self, record: dict) -> dict: ...


class CostPort(Protocol):
    def execute(self, name: str, arguments: dict) -> dict: ...


class WorkloadPort(Protocol):
    def prepare(self, name: str, arguments: dict) -> dict: ...
    def execute_operation(self, record: dict) -> dict: ...
    def status(self, record: dict) -> dict: ...
    def discover(self) -> list[dict]: ...


class FactoryApiPort(Protocol):
    def health(self) -> dict: ...
    def creation_capabilities(self) -> dict: ...
    def openapi(self) -> dict: ...
    def catalog_list(self, folder: str) -> dict: ...
    def catalog_settings(self, folder: str, factory_id: str, scale_set_id: str, project_id: str) -> dict: ...
    def catalog_prepare(self, body: dict) -> dict: ...
    def catalog_confirm(self, folder: str, confirmation_id: str) -> dict: ...


class ConversationPort(Protocol):
    def answer(self, question: str, audience: str, principal: Principal, scope_key: str) -> dict: ...


class ResponseUsage(Protocol):
    input_tokens: int
    output_tokens: int


class ResponseItem(Protocol):
    type: str
    name: str
    arguments: str
    call_id: str
    def model_dump(self, *, exclude_none: bool) -> dict: ...


class ModelResponse(Protocol):
    id: str
    status: str
    output_text: str
    output: list[ResponseItem]
    usage: ResponseUsage | None


class ModelSession(Protocol):
    def respond(self, messages: list[dict], reference: dict) -> ModelResponse: ...


class ModelGateway(Protocol):
    def open(self, settings: Settings) -> AbstractContextManager[ModelSession]: ...


class AuditPort(Protocol):
    def operation(self, name: str, call_id: str | None = None) -> AbstractContextManager[dict]: ...
