trigger:
  branches:
    include:
      - release/project*

variables:
- template: ../variables/variables.yaml

stages:
- stage: Dev
  displayName: Dev
  variables:
    dev_test_prod: "dev"
    dev_test_prod_sub_id: "$(dev_sub_id)"
    dev_test_prod_ado_service_connection: $(dev_service_connection)
    admin_projectType: "esml"
  jobs:
    - deployment: ESML_Networking
      displayName: Deploy networking for project with Bicep
      pool:
        vmImage: windows-latest
      environment: Dev  
      strategy:
        runOnce:
          deploy:
            steps:
              - template: ./jobs/job-1-networking.yaml
    - deployment: ESML_Services
      dependsOn: ESML_Networking
      displayName: Deploy Azure services for project with Bicep
      pool:
        vmImage: windows-latest
      environment: Dev  
      strategy:
        runOnce:
          deploy:
            steps:
              - template: ./jobs/job-2-esml-services.yaml
- stage: Stage
  displayName: Stage
  variables:
    dev_test_prod: "test"
    dev_test_prod_sub_id: "$(test_sub_id)"
    dev_test_prod_ado_service_connection: $(test_service_con_connection)
    admin_projectType: "esml"
  jobs:
    - deployment: ESML_Networking
      displayName: Deploy networking for project with Bicep
      pool:
        vmImage: windows-latest
      environment: Stage  
      strategy:
        runOnce:
          deploy:
            steps:
              - template: ./jobs/job-1-networking.yaml
    - deployment: ESML_Services
      dependsOn: ESML_Networking
      displayName: Deploy Azure services for project with Bicep
      pool:
        vmImage: windows-latest
      environment: Stage  
      strategy:
        runOnce:
          deploy:
            steps:
              - template: ./jobs/job-2-esml-services.yaml
- stage: Prod
  displayName: Prod
  variables:
    dev_test_prod: "prod"
    dev_test_prod_sub_id: "$(prod_sub_id)"
    dev_test_prod_ado_service_connection: $(prod_service_con_connection)
    admin_projectType: "esml"
  jobs:
    - deployment: ESML_Networking
      displayName: Deploy networking for project with Bicep
      pool:
        vmImage: windows-latest
      environment: Prod  
      strategy:
        runOnce:
          deploy:
            steps:
              - template: ./jobs/job-1-networking.yaml
    - deployment: ESML_Services
      dependsOn: ESML_Networking
      displayName: Deploy Azure services for project with Bicep
      pool:
        vmImage: windows-latest
      environment: Prod
      strategy:
        runOnce:
          deploy:
            steps:
              - template: ./jobs/job-2-esml-services.yaml