#
#Dev_GenAI_Project:
#✅ Runs automatically on CI triggers (release/project* branches and main)
#✅ Runs on manual triggers
#
#Stage_GenAI_Project:
#❌ Never runs automatically - requires manual trigger
#✅ Only runs when manually triggered AND Dev succeeded
#✅ Can be manually triggered from any branch (no branch restrictions)
#
#Prod_GenAI_Project:
#❌ Never runs automatically - requires manual trigger
#✅ Only runs when manually triggered AND (Stage succeeded/skipped OR Dev succeeded)
#✅ Can be manually triggered from any branch
#

trigger:
  branches:
    include:
      - release/project*
      #- main
variables:
  - template: ../variables/variables.yaml
stages:
- stage: Dev_GenAI_Project
  displayName: Dev GenAI Project
  variables:
    dev_test_prod: "dev"
    dev_test_prod_sub_id: "$(dev_sub_id)"
    network_env: "$(network_env_dev)"
  jobs:
    - deployment: ESGenAI_Networking
      condition: and(eq(variables['runNetworkingVar'], 'true'),eq(variables['BYO_subnets'], 'false'))
      displayName: Deploy Private Network
      timeoutInMinutes: 120
      pool:
        vmImage: windows-2022
      environment: Dev  
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self
                submodules: recursive
                fetchDepth: 0
                displayName: 'Checkout with submodules'
              - template: ./jobs/job-1-genai-networking.yaml
                parameters:
                  serviceConnection: ${{ variables.dev_service_connection }}
                  serviceConnectionSeeding: ${{ variables.dev_seeding_kv_service_connection }}
    - deployment: ESGenAI_Services
      condition: or(succeeded(), eq(variables['runNetworkingVar'], 'false'), eq(variables['BYO_subnets'], 'true'))
      dependsOn: ESGenAI_Networking
      displayName: Deploy GenAI services,Personas,RBAC,ACL,CAF & WAF Policys
      timeoutInMinutes: 240  # Increased timeout to accommodate retries
      pool:
        vmImage: windows-2022
      environment: Dev  
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self
                submodules: recursive
                fetchDepth: 0
                displayName: 'Checkout with submodules'
              - template: ./jobs/job-2-genai-services.yaml
                parameters:
                  serviceConnection: ${{ variables.dev_service_connection }}
                  serviceConnectionSeeding: ${{ variables.dev_seeding_kv_service_connection }}
- stage: Stage_GenAI_Project
  displayName: Stage GenAI Project
  condition: and(eq(variables['Build.Reason'], 'Manual'), in(dependencies.Dev_GenAI_Project.result, 'Succeeded'))
  dependsOn: Dev_GenAI_Project
  variables:
    dev_test_prod: "test"
    dev_test_prod_sub_id: "$(test_sub_id)"
    network_env: "$(network_env_stage)"
  jobs:
    - deployment: ESGenAI_Networking
      condition: and(eq(variables['runNetworkingVar'], 'true'),eq(variables['BYO_subnets'], 'false'))
      displayName: Deploy Private Network
      timeoutInMinutes: 240
      pool:
        vmImage: windows-2022
      environment: Stage  
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self
                submodules: recursive
                fetchDepth: 0
                displayName: 'Checkout with submodules'
              - template: ./jobs/job-1-genai-networking.yaml
                parameters:
                  serviceConnection: ${{ variables.test_service_connection }}
                  serviceConnectionSeeding: ${{ variables.test_seeding_kv_service_connection }}
    - deployment: ESGenAI_Services
      condition: or(succeeded(), eq(variables['runNetworkingVar'], 'false'), eq(variables['BYO_subnets'], 'true'))
      dependsOn: ESGenAI_Networking
      displayName: Deploy GenAI services,Personas,RBAC,ACL,CAF & WAF Policys
      timeoutInMinutes: 240  # Increased timeout to accommodate retries
      pool:
        vmImage: windows-2022
      environment: Stage  
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self
                submodules: recursive
                fetchDepth: 0
                displayName: 'Checkout with submodules'
              - template: ./jobs/job-2-genai-services.yaml
                parameters:
                  serviceConnection: ${{ variables.test_service_connection }}
                  serviceConnectionSeeding: ${{ variables.test_seeding_kv_service_connection }}
- stage: Prod_GenAI_Project
  displayName: Prod GenAI Project
  condition: and(eq(variables['Build.Reason'], 'Manual'), or(in(dependencies.Stage_GenAI_Project.result, 'Succeeded', 'Skipped'), in(dependencies.Dev_GenAI_Project.result, 'Succeeded')))
  dependsOn: 
    - Stage_GenAI_Project
    - Dev_GenAI_Project
  variables:
    dev_test_prod: "prod"
    dev_test_prod_sub_id: "$(prod_sub_id)"
    network_env: "$(network_env_prod)"
  jobs:
    - deployment: ESGenAI_Networking
      condition: and(eq(variables['runNetworkingVar'], 'true'),eq(variables['BYO_subnets'], 'false'))
      displayName: Deploy Private Network
      timeoutInMinutes: 120
      pool:
        vmImage: windows-2022
      environment: Prod  
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self
                submodules: recursive
                fetchDepth: 0
                displayName: 'Checkout with submodules'
              - template: ./jobs/job-1-genai-networking.yaml
                parameters:
                  serviceConnection: ${{ variables.prod_service_connection }}
                  serviceConnectionSeeding: ${{ variables.prod_seeding_kv_service_connection }}
    - deployment: ESGenAI_Services
      condition: or(succeeded(), eq(variables['runNetworkingVar'], 'false'), eq(variables['BYO_subnets'], 'true'))
      dependsOn: ESGenAI_Networking
      displayName: Deploy GenAI services,Personas,RBAC,ACL,CAF & WAF Policys
      timeoutInMinutes: 240  # Increased timeout to accommodate retries
      pool:
        vmImage: windows-2022
      environment: Prod
      variables:
        dev_test_prod: "prod"
        dev_test_prod_sub_id: "$(prod_sub_id)"
        network_env: "$(network_env_prod)"
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self
                submodules: recursive
                fetchDepth: 0
                displayName: 'Checkout with submodules'
              - template: ./jobs/job-2-genai-services.yaml
                parameters:
                  serviceConnection: ${{ variables.prod_service_connection }}
                  serviceConnectionSeeding: ${{ variables.prod_seeding_kv_service_connection }}
