trigger:
  branches:
    include:
      - release/project*

variables:
- template: ../variables/variables.yaml
- name: runNetworkingVar
  value: true

parameters:
- name: runNetworking
  displayName: 'Run Networking'
  type: boolean
  default: true

stages:
- stage: Dev
  displayName: Dev
  variables:
    dev_test_prod: "dev"
    dev_test_prod_sub_id: "$(dev_sub_id)"
    admin_projectType: "esml"
  jobs:
    - deployment: ESML_Networking
      displayName: Deploy networking for project with Bicep
      pool: 
        vmImage: windows-latest
      environment: Dev
      condition: eq(variables['runNetworkingVar'], 'true')
      strategy:
        runOnce:
          deploy:
            steps:
              - template: ./jobs/job-1-esml-networking.yaml
                parameters:
                  serviceConnection: ${{ variables.dev_service_connection }}
    - deployment: ESML_Services
      dependsOn: ESML_Networking
      condition: always()
      displayName: Deploy Azure services for project with Bicep
      variables:
        dev_test_prod: "dev"
        dev_test_prod_sub_id: "$(dev_sub_id)"
        admin_projectType: "esml"
      pool:
        vmImage: windows-latest
      environment: Dev  
      strategy:
        runOnce:
          deploy:
            steps:
              - template: ./jobs/job-2-esml-services.yaml
                parameters:
                  serviceConnection: ${{ variables.dev_service_connection }}
- stage: Stage
  displayName: Stage
  variables:
    dev_test_prod: "test"
    dev_test_prod_sub_id: "$(test_sub_id)"
    admin_projectType: "esml"
  jobs:
    - deployment: ESML_Networking
      displayName: Deploy networking for project with Bicep
      pool:
        vmImage: windows-latest
      environment: Stage  
      strategy:
        runOnce:
          deploy:
            steps:
              - template: ./jobs/job-1-esml-networking.yaml
                parameters:
                  serviceConnection: ${{ variables.test_service_connection }}
    - deployment: ESML_Services
      dependsOn: ESML_Networking
      displayName: Deploy Azure services for project with Bicep
      pool:
        vmImage: windows-latest
      environment: Stage  
      strategy:
        runOnce:
          deploy:
            steps:
              - template: ./jobs/job-2-esml-services.yaml
                parameters:
                  serviceConnection: ${{ variables.test_service_connection }}
- stage: Prod
  displayName: Prod
  variables:
    dev_test_prod: "prod"
    dev_test_prod_sub_id: "$(prod_sub_id)"
    admin_projectType: "esml"
  jobs:
    - deployment: ESML_Networking
      displayName: Deploy networking for project with Bicep
      pool:
        vmImage: windows-latest
      environment: Prod  
      strategy:
        runOnce:
          deploy:
            steps:
              - template: ./jobs/job-1-esml-networking.yaml
                parameters:
                  serviceConnection: ${{ variables.prod_service_connection }}
    - deployment: ESML_Services
      dependsOn: ESML_Networking
      displayName: Deploy Azure services for project with Bicep
      pool:
        vmImage: windows-latest
      environment: Prod
      strategy:
        runOnce:
          deploy:
            steps:
              - template: ./jobs/job-2-esml-services.yaml
                parameters:
                  serviceConnection: ${{ variables.prod_service_connection }}