trigger:
  branches:
    include:
      - release/project*
      - main
variables:
- template: ../variables/variables.yaml

stages:
- stage: Dev_GenAI_Project
  displayName: Dev GenAI Project
  variables:
    dev_test_prod: "dev"
    dev_test_prod_sub_id: "$(dev_sub_id)"
    admin_projectType: "genai-1"
    network_env: "$(network_env_dev)"
  jobs:
    - deployment: ESGenAI_Networking
      condition: and(eq(variables['runNetworkingVar'], 'true'),eq(variables['BYO_subnets'], 'false'))
      displayName: Deploy Private Network
      timeoutInMinutes: 120
      pool:
        vmImage: windows-2022
      environment: Dev  
      strategy:
        runOnce:
          deploy:
            steps:
              - template: ./jobs/job-1-genai-networking.yaml
                parameters:
                  serviceConnection: ${{ variables.dev_service_connection }}
                  serviceConnectionSeeding: ${{ variables.dev_seeding_kv_service_connection }}
    - deployment: ESGenAI_Services
      condition: or(succeeded(), eq(variables['runNetworkingVar'], 'false'), eq(variables['BYO_subnets'], 'true'))
      dependsOn: ESGenAI_Networking
      displayName: Deploy GenAI services,Personas,RBAC,ACL,CAF & WAF Policys
      timeoutInMinutes: 240  # Increased timeout to accommodate retries
      pool:
        vmImage: windows-2022
      environment: Dev  
      strategy:
        runOnce:
          deploy:
            steps:
              - template: ./jobs/job-2-genai-services.yaml
                parameters:
                  serviceConnection: ${{ variables.dev_service_connection }}
                  serviceConnectionSeeding: ${{ variables.dev_seeding_kv_service_connection }}
              # First Retry: Wait and retry on failure (if enabled and maxRetryAttempts >= 2)
              - task: PowerShell@2
                displayName: 'Wait before retry 1'
                condition: and(failed(), eq(variables['enableRetries'], 'true'), ge(variables['maxRetryAttempts'], '2'))
                inputs:
                  targetType: 'inline'
                  script: |
                    $retryMinutes = "$(retryMinutes)"
                    $retrySeconds = [int]$retryMinutes * 60
                    Write-Host "Attempt 1 failed. Waiting $retryMinutes minutes ($retrySeconds seconds) before retry 1..."
                    Start-Sleep -Seconds $retrySeconds
                    Write-Host "Wait completed. Starting retry attempt 1..."
              - template: ./jobs/job-2-genai-services.yaml
                parameters:
                  serviceConnection: ${{ variables.dev_service_connection }}
                  serviceConnectionSeeding: ${{ variables.dev_seeding_kv_service_connection }}
              # Second Retry: Wait and retry on failure (if enabled and maxRetryAttempts >= 3)
              - task: PowerShell@2
                displayName: 'Wait before retry 2'
                condition: and(failed(), eq(variables['enableRetries'], 'true'), ge(variables['maxRetryAttempts'], '3'))
                inputs:
                  targetType: 'inline'
                  script: |
                    $retryMinutesExtended = "$(retryMinutesExtended)"
                    $retrySeconds = [int]$retryMinutesExtended * 60
                    Write-Host "Attempt 2 failed. Waiting $retryMinutesExtended minutes ($retrySeconds seconds) before retry 2..."
                    Start-Sleep -Seconds $retrySeconds
                    Write-Host "Wait completed. Starting final retry attempt..."
              - template: ./jobs/job-2-genai-services.yaml
                parameters:
                  serviceConnection: ${{ variables.dev_service_connection }}
                  serviceConnectionSeeding: ${{ variables.dev_seeding_kv_service_connection }}
- stage: Stage_GenAI_Project
  displayName: Stage GenAI Project
  condition: ne(variables['Build.SourceBranch'], 'refs/heads/main')
  variables:
    dev_test_prod: "test"
    dev_test_prod_sub_id: "$(test_sub_id)"
    admin_projectType: "genai-1"
    network_env: "$(network_env_stage)"
  jobs:
    - deployment: ESGenAI_Networking
      condition: and(eq(variables['runNetworkingVar'], 'true'),eq(variables['BYO_subnets'], 'false'))
      displayName: Deploy Private Network
      timeoutInMinutes: 240
      pool:
        vmImage: windows-2022
      environment: Stage  
      strategy:
        runOnce:
          deploy:
            steps:
              - template: ./jobs/job-1-genai-networking.yaml
                parameters:
                  serviceConnection: ${{ variables.test_service_connection }}
                  serviceConnectionSeeding: ${{ variables.test_seeding_kv_service_connection }}
    - deployment: ESGenAI_Services
      condition: or(succeeded(), eq(variables['runNetworkingVar'], 'false'), eq(variables['BYO_subnets'], 'true'))
      dependsOn: ESGenAI_Networking
      displayName: Deploy GenAI services,Personas,RBAC,ACL,CAF & WAF Policys
      timeoutInMinutes: 240  # Increased timeout to accommodate retries
      pool:
        vmImage: windows-2022
      environment: Stage  
      strategy:
        runOnce:
          deploy:
            steps:
              - template: ./jobs/job-2-genai-services.yaml
                parameters:
                  serviceConnection: ${{ variables.test_service_connection }}
                  serviceConnectionSeeding: ${{ variables.test_seeding_kv_service_connection }}
              # First Retry: Wait and retry on failure (if enabled and maxRetryAttempts >= 2)
              - task: PowerShell@2
                displayName: 'Wait before retry 1'
                condition: and(failed(), eq(variables['enableRetries'], 'true'), ge(variables['maxRetryAttempts'], '2'))
                inputs:
                  targetType: 'inline'
                  script: |
                    $retryMinutes = "$(retryMinutes)"
                    $retrySeconds = [int]$retryMinutes * 60
                    Write-Host "Attempt 1 failed. Waiting $retryMinutes minutes ($retrySeconds seconds) before retry 1..."
                    Start-Sleep -Seconds $retrySeconds
                    Write-Host "Wait completed. Starting retry attempt 1..."
              - template: ./jobs/job-2-genai-services.yaml
                parameters:
                  serviceConnection: ${{ variables.test_service_connection }}
                  serviceConnectionSeeding: ${{ variables.test_seeding_kv_service_connection }}
              # Second Retry: Wait and retry on failure (if enabled and maxRetryAttempts >= 3)
              - task: PowerShell@2
                displayName: 'Wait before retry 2'
                condition: and(failed(), eq(variables['enableRetries'], 'true'), ge(variables['maxRetryAttempts'], '3'))
                inputs:
                  targetType: 'inline'
                  script: |
                    $retryMinutesExtended = "$(retryMinutesExtended)"
                    $retrySeconds = [int]$retryMinutesExtended * 60
                    Write-Host "Attempt 2 failed. Waiting $retryMinutesExtended minutes ($retrySeconds seconds) before retry 2..."
                    Start-Sleep -Seconds $retrySeconds
                    Write-Host "Wait completed. Starting final retry attempt..."
              - template: ./jobs/job-2-genai-services.yaml
                parameters:
                  serviceConnection: ${{ variables.test_service_connection }}
                  serviceConnectionSeeding: ${{ variables.test_seeding_kv_service_connection }}
- stage: Prod_GenAI_Project
  displayName: Prod GenAI Project
  condition: ne(variables['Build.SourceBranch'], 'refs/heads/main')
  variables:
    dev_test_prod: "prod"
    dev_test_prod_sub_id: "$(prod_sub_id)"
    admin_projectType: "genai-1"
    network_env: "$(network_env_prod)"
  jobs:
    - deployment: ESGenAI_Networking
      condition: and(eq(variables['runNetworkingVar'], 'true'),eq(variables['BYO_subnets'], 'false'))
      displayName: Deploy Private Network
      timeoutInMinutes: 120
      pool:
        vmImage: windows-2022
      environment: Prod  
      strategy:
        runOnce:
          deploy:
            steps:
              - template: ./jobs/job-1-genai-networking.yaml
                parameters:
                  serviceConnection: ${{ variables.prod_service_connection }}
                  serviceConnectionSeeding: ${{ variables.prod_seeding_kv_service_connection }}
    - deployment: ESGenAI_Services
      condition: or(succeeded(), eq(variables['runNetworkingVar'], 'false'), eq(variables['BYO_subnets'], 'true'))
      dependsOn: ESGenAI_Networking
      displayName: Deploy GenAI services,Personas,RBAC,ACL,CAF & WAF Policys
      timeoutInMinutes: 240  # Increased timeout to accommodate retries
      pool:
        vmImage: windows-2022
      environment: Prod
      variables:
        dev_test_prod: "prod"
        dev_test_prod_sub_id: "$(prod_sub_id)"
        admin_projectType: "genai-1"
        network_env: "$(network_env_prod)"
      strategy:
        runOnce:
          deploy:
            steps:
              - template: ./jobs/job-2-genai-services.yaml
                parameters:
                  serviceConnection: ${{ variables.prod_service_connection }}
                  serviceConnectionSeeding: ${{ variables.prod_seeding_kv_service_connection }}
              # First Retry: Wait and retry on failure (if enabled and maxRetryAttempts >= 2)
              - task: PowerShell@2
                displayName: 'Wait before retry 1'
                condition: and(failed(), eq(variables['enableRetries'], 'true'), ge(variables['maxRetryAttempts'], '2'))
                inputs:
                  targetType: 'inline'
                  script: |
                    $retryMinutes = "$(retryMinutes)"
                    $retrySeconds = [int]$retryMinutes * 60
                    Write-Host "Attempt 1 failed. Waiting $retryMinutes minutes ($retrySeconds seconds) before retry 1..."
                    Start-Sleep -Seconds $retrySeconds
                    Write-Host "Wait completed. Starting retry attempt 1..."
              - template: ./jobs/job-2-genai-services.yaml
                parameters:
                  serviceConnection: ${{ variables.prod_service_connection }}
                  serviceConnectionSeeding: ${{ variables.prod_seeding_kv_service_connection }}
              # Second Retry: Wait and retry on failure (if enabled and maxRetryAttempts >= 3)
              - task: PowerShell@2
                displayName: 'Wait before retry 2'
                condition: and(failed(), eq(variables['enableRetries'], 'true'), ge(variables['maxRetryAttempts'], '3'))
                inputs:
                  targetType: 'inline'
                  script: |
                    $retryMinutesExtended = "$(retryMinutesExtended)"
                    $retrySeconds = [int]$retryMinutesExtended * 60
                    Write-Host "Attempt 2 failed. Waiting $retryMinutesExtended minutes ($retrySeconds seconds) before retry 2..."
                    Start-Sleep -Seconds $retrySeconds
                    Write-Host "Wait completed. Starting final retry attempt..."
              - template: ./jobs/job-2-genai-services.yaml
                parameters:
                  serviceConnection: ${{ variables.prod_service_connection }}
                  serviceConnectionSeeding: ${{ variables.prod_seeding_kv_service_connection }}
