trigger:
  branches:
    include:
      - release/project*

variables:
- template: ../variables/variables.yaml
- name: runNetworkingVar
  value: true

parameters:
- name: runNetworking
  displayName: 'Enable Networking'
  type: boolean
  default: true

stages:
- stage: Dev_ESML_Project
  displayName: Dev ESML Project
  variables:
    dev_test_prod: "dev"
    dev_test_prod_sub_id: "$(dev_sub_id)"
    admin_projectType: "esml"
  jobs:
    - deployment: ESML_Networking
      condition: eq(variables['runNetworkingVar'], 'true')
      displayName: Deploy Private Network
      pool: 
        vmImage: windows-latest
      environment: Dev      
      strategy:
        runOnce:
          deploy:
            steps:
              - template: ./jobs/job-1-esml-networking.yaml
                parameters:
                  serviceConnection: ${{ variables.dev_service_connection }}
    - deployment: ESML_Services
      condition: or(succeeded(), eq(variables['runNetworkingVar'], 'false'))
      dependsOn: ESML_Networking
      displayName: Deploy ESML services,Personas,RBAC,ACL,CAF & WAF Policys
      variables:
        dev_test_prod: "dev"
        dev_test_prod_sub_id: "$(dev_sub_id)"
        admin_projectType: "esml"
      pool:
        vmImage: windows-latest
      environment: Dev  
      strategy:
        runOnce:
          deploy:
            steps:
              - template: ./jobs/job-2-esml-services.yaml
                parameters:
                  serviceConnection: ${{ variables.dev_service_connection }}
- stage: Stage_ESML_Project
  displayName: Stage ESML Project
  variables:
    dev_test_prod: "test"
    dev_test_prod_sub_id: "$(test_sub_id)"
    admin_projectType: "esml"
  jobs:
    - deployment: ESML_Networking
      condition: eq(variables['runNetworkingVar'], 'true')
      displayName: Deploy Private Network
      pool:
        vmImage: windows-latest
      environment: Stage  
      strategy:
        runOnce:
          deploy:
            steps:
              - template: ./jobs/job-1-esml-networking.yaml
                parameters:
                  serviceConnection: ${{ variables.test_service_connection }}
    - deployment: ESML_Services
      condition: or(succeeded(), eq(variables['runNetworkingVar'], 'false'))
      dependsOn: ESML_Networking
      displayName: DDeploy ESML services,Personas,RBAC,ACL,CAF & WAF Policys
      pool:
        vmImage: windows-latest
      environment: Stage  
      strategy:
        runOnce:
          deploy:
            steps:
              - template: ./jobs/job-2-esml-services.yaml
                parameters:
                  serviceConnection: ${{ variables.test_service_connection }}
- stage: Prod_ESML_Project
  displayName: Prod ESML Project
  variables:
    dev_test_prod: "prod"
    dev_test_prod_sub_id: "$(prod_sub_id)"
    admin_projectType: "esml"
  jobs:
    - deployment: ESML_Networking
      condition: eq(variables['runNetworkingVar'], 'true')
      displayName: Deploy Private Network
      pool:
        vmImage: windows-latest
      environment: Prod  
      strategy:
        runOnce:
          deploy:
            steps:
              - template: ./jobs/job-1-esml-networking.yaml
                parameters:
                  serviceConnection: ${{ variables.prod_service_connection }}
    - deployment: ESML_Services
      condition: or(succeeded(), eq(variables['runNetworkingVar'], 'false'))
      dependsOn: ESML_Networking
      displayName: DDeploy ESML services,Personas,RBAC,ACL,CAF & WAF Policys
      pool:
        vmImage: windows-latest
      environment: Prod
      strategy:
        runOnce:
          deploy:
            steps:
              - template: ./jobs/job-2-esml-services.yaml
                parameters:
                  serviceConnection: ${{ variables.prod_service_connection }}