trigger: none
  # branches:
    # include:
      # - main*
variables:
- template: ../variables/variables.yaml
- name: runNetworkingVar
  value: true

stages:
# Dev:
# ✅ Runs automatically on CI triggers (main branch), if you uncomment code and remove "none" value
# ✅ Runs on manual triggers
- stage: Dev
  displayName: AIFactory_CMN_Dev
  variables:
    dev_test_prod: "dev"
    dev_test_prod_sub_id: $(dev_sub_id)
    cidr_range: $(dev_cidr_range)
    network_env: "$(network_env_dev)"
    admin_bicep_input_keyvault_subscription: "$(dev_admin_bicep_input_keyvault_subscription)"
    admin_bicep_kv_fw_rg: "$(dev_admin_bicep_kv_fw_rg)"
    admin_bicep_kv_fw: "$(dev_admin_bicep_kv_fw)"
  jobs:
    - deployment: AIFactory_CMN_Dev
      displayName: AIFactory_CMN_Dev
      pool:
        vmImage: windows-2022
      environment: Dev  
      strategy:
        runOnce:
          deploy:
            steps:
              - template: ./jobs/job-1-aif-cmn.yaml
                parameters:
                  serviceConnection: ${{ variables.dev_service_connection }}

# Stage:
# ❌ Never runs automatically - requires manual trigger
# ✅ Only runs when manually triggered AND Dev succeeded
# ✅ Can be manually triggered from any branch (no branch restrictions)
- stage: Stage
  dependsOn: Dev
  condition: eq(variables['Build.Reason'], 'Manual')
  displayName: AIFactory_CMN_Stage
  variables:
    dev_test_prod: "test"
    dev_test_prod_sub_id: $(test_sub_id)
    cidr_range: $(test_cidr_range)
    network_env: "$(network_env_stage)"
    admin_bicep_input_keyvault_subscription: "$(test_admin_bicep_input_keyvault_subscription)"
    admin_bicep_kv_fw_rg: "$(test_admin_bicep_kv_fw_rg)"
    admin_bicep_kv_fw: "$(test_admin_bicep_kv_fw)"
  jobs:
    - deployment: AIFactory_CMN_Stage
      displayName: AIFactory_CMN_Stage
      pool:
        vmImage: windows-2022
      environment: Stage
      strategy:
        runOnce:
          deploy:
            steps:
              - template: ./jobs/job-1-aif-cmn.yaml
                parameters:
                  serviceConnection: ${{ variables.test_service_connection }}

# Prod:
# ❌ Never runs automatically - requires manual trigger
# ✅ Only runs when manually triggered AND (Stage succeeded/skipped OR Dev succeeded)
# ✅ Can be manually triggered from any branch
- stage: Prod
  dependsOn: 
    - Dev
    - Stage
  condition: |
    and(
      eq(variables['Build.Reason'], 'Manual'),
      or(
        in(dependencies.Stage.result, 'Succeeded', 'Skipped'),
        eq(dependencies.Dev.result, 'Succeeded')
      )
    )
  displayName: AIFactory_CMN_Prod
  variables:
    dev_test_prod: "prod"
    dev_test_prod_sub_id: $(prod_sub_id)
    cidr_range: $(prod_cidr_range)
    network_env: "$(network_env_prod)"
    admin_bicep_input_keyvault_subscription: "$(prod_admin_bicep_input_keyvault_subscription)"
    admin_bicep_kv_fw_rg: "$(prod_admin_bicep_kv_fw_rg)"
    admin_bicep_kv_fw: "$(prod_admin_bicep_kv_fw)"
  jobs:
    - deployment: AIFactory_CMN_Prod
      displayName: AIFactory_CMN_Prod
      pool:
        vmImage: windows-2022
      environment: Prod
      strategy:
        runOnce:
          deploy:
            steps:
              - template: ./jobs/job-1-aif-cmn.yaml
                parameters:
                  serviceConnection: ${{ variables.prod_service_connection }}
  