trigger:
  branches:
    include:
      - main

variables:
- template: ../variables/variables.yaml

stages:
- stage: Dev
  displayName: AIFactory_Common_Dev
  variables:
    dev_test_prod: "dev"
    dev_test_prod_sub_id: $(dev_sub_id)
    dev_test_prod_ado_service_connection: $(dev_service_connection)
  jobs:
    - deployment: AIFactory_Common_Dev
      displayName: AIFactory_Common_Dev
      pool:
        vmImage: windows-latest
      environment: Dev  
      strategy:
        runOnce:
          deploy:
            steps:
              - template: ./jobs/job-1-aif-cmn.yaml

- stage: Stage
  dependsOn: Dev
  displayName: AIFactory_Common_Stage
  variables:
    dev_test_prod: "test"
    dev_test_prod_sub_id: $(test_sub_id)
    dev_test_prod_ado_service_connection: $(test_service_connection)
  jobs:
    - deployment: AIFactory_Common_Stage
      displayName: AIFactory_Common_Stage
      pool:
        vmImage: windows-latest
      environment: Stage
      strategy:
        runOnce:
          deploy:
            steps:
              - template: ./jobs/job-1-aif-cmn.yaml

- stage: Prod
  dependsOn: Stage
  displayName: AIFactory_Common_Prod
  variables:
    dev_test_prod: "prod"
    dev_test_prod_sub_id: $(prod_sub_id)
    dev_test_prod_ado_service_connection: $(prod_service_connection)
  jobs:
    - deployment: AIFactory_Common_Prod
      displayName: AIFactory_Common_Prod
      pool:
        vmImage: windows-latest
      environment: Prod
      strategy:
        runOnce:
          deploy:
            steps:
              - template: ./jobs/job-1-aif-cmn.yaml
  