.\26-add-esml-project-member.ps1 `
-spSecret 'abc' ` # Specifies the secret for service principal
-spID 'abc' ` # Specifies the App id for service principal
-tenantID 'abc' ` # Specifies the secret for service principal
-subscriptionID 'abc' ` # Specifies the secret for service principal
-storageAccount 'abc' ` # ESML AIFactory datalake name
-adlsgen2filesystem 'abc' ` # Override the default ESML datalake container called: lake3
-projectXXX 'abc' ` # ESMLProject number: project001
-userObjectIds 'x','y','z' ` # Array of user Object Ids
-projectSPObjectID 'abc' ` # Project service principle OID esml-project001-sp-oid
-commonSPObjectID 'abc' ` # Common service principle OID common
-commonADgroupObjectID 'abc' ` # Common AD group OID common. Set to TODO to ignore
-projectADGroupObjectId 'abc' ` # Project AD group OID common. Set to TODO to ignore
-targetObjectID 'abc' ` # Specifies the object id for service principal, to assign GET, LIST Access policy
-projectKeyvaultName 'abc' ` # keyvault name: [kv-prj001-pgvr2-001, kv-cmndev-pgvr2-001]
-commonRGNamePrefix 'abc' ` # ESML AIFactory suffix. What suffix on common resources: abc-def-
-commonResourceSuffix 'abc' ` # ESML AIFactory suffix. What suffix on common resource group: -001
-aifactorySuffixRG 'abc' ` # ESML AIFactory suffix. What suffix on common resource group: -001
-locationSuffix 'abc' ` # Region location prefix in ESML settings: [weu,uks,swe,sdc]
-projectNumber 'abc' ` # ESML Projectnumber, three digits: 001
-env 'abc' # ESML AIFactory environment: [dev,test,prod]