name: project-esml-test-infra-deploy.yml

on:
    #push:
    workflow_dispatch:

env:
    admin_aifactorySuffixRG: "-001"
    admin_bicep_input_keyvault_subscription: "a1234567-xxxx-xxxx-xxxx-xxxxxxxxxxxx" # seeding keyvault, subscription id
    admin_bicep_kv_fw: "seeding-kv-name" # seeding keyvault, name
    admin_bicep_kv_fw_rg: "aifactory-rg" #seeding keyvault, resource group
    project_service_principal_AppID_seeding_kv_name: "esml-project001-sp-id" # Service principle ID, name from seeding keyvault (need to be from enterprise application)
    project_service_principal_OID_seeding_kv_name: "esml-project001-sp-oid" # Service principle Object ID, name from seeding keyvault (need to be from enterprise application)
    project_service_principal_Secret_seeding_kv_name: "esml-project001-sp-secret" # Service principle secret, name from seeding keyvault
    admin_commonResourceSuffix: "-001"
    admin_ip_fw: "192.x.x.x"
    admin_location: "westeurope"
    admin_locationSuffix: "weu"
    admin_prjResourceSuffix: "-001"
    test_sub_id: "a1234567-xxxx-xxxx-xxxx-xxxxxxxxxxxx" # SubscriptionID test
    project_IP_whitelist: "192.x.x.x"
    project_number_000: "001" # Project number (3 digits)
    technical_admins_ad_object_id: "012345ab-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
    technical_admins_email: "adminemail@example.com"
    common-sp-appid-seeding-kv-name: "esml-common-bicep-sp-id"
    common-sp-secret-seeding-kv-name: "esml-common-bicep-sp-secret"

jobs:
  test-project-deploy:
    name: Deploy to Test
    environment:
      name: stage
    runs-on: ubuntu-latest
    env:
      dev_test_prod: "test"
    steps:
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true
    - name: GIT
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: 10_Get ADO IP for agent
      uses: azure/powershell@v2
      with:
        inlineScript: |
          $resp = $resp = Invoke-RestMethod http://ipinfo.io/json | Select -exp ip
                  Write-Host $resp
                  Write-Host "##vso[task.setvariable variable=admin_ip_fw]$resp"
                  $ipAddr = $resp
                  Write-Host ipAddr is: ${{ env.admin_ip_fw }}
        azPSVersion: latest
    - name: 10_Set ADO IP to keyvault FW whitelist
      uses: azure/cli@v2
      with:
        inlineScript: az keyvault network-rule add --subscription ${{ env.admin_bicep_input_keyvault_subscription }} --resource-group ${{ env.admin_bicep_kv_fw_rg }} --name ${{ env.admin_bicep_kv_fw }} --ip-address ${{ env.admin_ip_fw }}
        azcliversion: latest
    - name: 10_download_keyvault_secrets
      uses: azure/cli@v2
      with:
        inlineScript: |
          echo "common-sp-appid-value=$(az keyvault secret show --subscription ${{ env.admin_bicep_input_keyvault_subscription }}  --vault-name ${{ env.admin_bicep_kv_fw }} --name ${{ env.common-sp-appid-seeding-kv-name }} --query 'value' --output tsv)" >> $GITHUB_ENV
          echo "common-sp-secret-value=$(az keyvault secret show --subscription ${{ env.admin_bicep_input_keyvault_subscription }} --vault-name ${{ env.admin_bicep_kv_fw }} --name ${{ env.common-sp-secret-seeding-kv-name }} --query 'value' --output tsv)" >> $GITHUB_ENV
        azcliversion: latest
    - name: Copy pipelineFunctions Module to Root
      uses: azure/powershell@v2
      with:
        inlineScript: |
          Copy-Item "${{ github.workspace }}\azure-enterprise-scale-ml\environment_setup\aifactory\bicep\scripts\modules" -Destination "${{ github.workspace }}\modules" -Recurse
        azPSVersion: latest
    - name: 20_Calculate subnet allocations_PS
      uses: azure/powershell@v2
      with:
        inlineScript: |
          sudo pwsh -Command "Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass -Force ; ${{ github.workspace }}/azure-enterprise-scale-ml/environment_setup/aifactory/bicep/scripts/subnetCalc.ps1 -bicepPar1 './aifactory/parameters/10-esml-globals-1.json' -bicepPar2 './aifactory/parameters/10-esml-globals-2-12_13_21_22.json' -bicepPar3 './aifactory/parameters/10-esml-globals-4-13_21_22.json' -bicepPar4 './aifactory/parameters/21-22-esml-prj-parameters.json' -bicepPar5 './aifactory/parameters/10-esml-globals-override.json' -filePath './aifactory/parameters/' -spObjId '${{ env.common-sp-appid-value }}' -spSecret '${{ env.common-sp-secret-value }}' -env '${{ env.dev_test_prod }}' -subscriptionId '${{ env.test_sub_id }}' -prjResourceSuffix '${{ env.admin_prjResourceSuffix }}' -aifactorySuffixRGADO '${{ env.admin_aifactorySuffixRG }}' -commonResourceSuffixADO '${{ env.admin_commonResourceSuffix }}' -locationADO '${{ env.admin_location }}' -locationSuffixADO '${{ env.admin_locationSuffix }}' -useServicePrincipal"
        azPSVersion: latest
    - name: 21_Deploy subnets and NSG
      uses: azure/cli@v2
      with:
        inlineScript: |
          az deployment group create \
          --name "esml-p${{ env.project_number_000 }}-${{ env.dev_test_prod }}-${{ env.admin_locationSuffix }}${{ env.admin_aifactorySuffixRG }}SubnetDeplProj" \
          --subscription "${{ env.test_sub_id }}" \
          --resource-group "$( cat "./aifactory/parameters/subnetParameters.json" | grep vnetResourceGroup -A1 | tail -n1 | cut -d: -f2 | tr -d " \"" )" \
          --template-file "azure-enterprise-scale-ml\environment_setup\aifactory\bicep\esml-project\21-network.bicep" \
          --parameters @"./aifactory/parameters/subnetParameters.json" \
          --parameters @"./aifactory/parameters/10-esml-globals-override.json" \
          --parameters env="${{ env.dev_test_prod }}" \
          --parameters projectNumber="${{ env.project_number_000 }}"
        azcliversion: latest
    - name: 21_to_22_Generate network parameters
      uses: azure/powershell@v2
      with:
        inlineScript: |
          sudo pwsh -Command "Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass -Force ; ${{ github.workspace }}/azure-enterprise-scale-ml/environment_setup/aifactory/bicep/scripts/genDynamicNetworkParamFile.ps1 -spObjId '${{ env.common-sp-appid-value }}' -spSecret '${{ env.common-sp-secret-value }}' -useServicePrincipal -bicepPar1 './aifactory/parameters/10-esml-globals-1.json' -bicepPar2 './aifactory/parameters/10-esml-globals-2-12_13_21_22.json' -bicepPar3 './aifactory/parameters/10-esml-globals-4-13_21_22.json' -bicepPar4 './aifactory/parameters/21-22-esml-prj-parameters.json' -bicepPar5 './aifactory/parameters/10-esml-globals-override.json' -filePath './aifactory/parameters/' -env '${{ env.dev_test_prod }}' -locationSuffixADO '${{ env.admin_locationSuffix }}' -aifactorySuffixRGADO '${{ env.admin_aifactorySuffixRG }}' -projectNumber '${{ env.project_number_000 }}' -subscriptionId '${{ env.test_sub_id }}' "
        azPSVersion: latest
    - name: 30_Sleep for 1 minute
      run: |
        write-host "Waiting for subnets to fully register to subscription"
        Start-Sleep 60
      shell: pwsh
    - name: 22_Deploy esml project
      uses: azure/cli@v2
      with:
        inlineScript: |
          az deployment sub create \
          --name "esml-p${{ env.project_number_000 }}-${{ env.dev_test_prod }}-${{ env.admin_locationSuffix }}-${{ env.admin_prjResourceSuffix }}${{ env.admin_commonResourceSuffix }}$PrjDepl" \
          --subscription "${{ env.test_sub_id }}" \
          --location "${{ env.admin_location }}" \
          --template-file "azure-enterprise-scale-ml\environment_setup\aifactory\bicep\esml-project\22-main.bicep" \
          --parameters adminPassword="$( date +%s | sha256sum | base64 | head -c 32 ; echo )" \
          --parameters @"./aifactory/parameters/10-esml-globals-1.json" \
          --parameters @"./aifactory/parameters/10-esml-globals-2-12_13_21_22.json" \
          --parameters @"./aifactory/parameters/10-esml-globals-3-12_13.json" \
          --parameters @"./aifactory/parameters/10-esml-globals-4-13_21_22.json" \
          --parameters @"./aifactory/parameters/10-esml-globals-5-13_23.json" \
          --parameters @"./aifactory/parameters/10-esml-globals-override.json" \
          --parameters @"./aifactory/parameters/21-22-esml-prj-parameters.json" \
          --parameters @"./aifactory/parameters/dynamicNetworkParams.json" \
          --parameters @"./aifactory/parameters/23-esml-prj-rbac-parameters.json" \
          --parameters env="${{ env.dev_test_prod }}" \
          --parameters projectNumber="${{ env.project_number_000 }}" \
          --parameters technicalAdminsObjectID="${{ env.technical_admins_ad_object_id }}" \
          --parameters technicalAdminsEmail="${{ env.technical_admins_email }}" \
          --parameters location="${{ env.admin_location }}" \
          --parameters locationSuffix="${{ env.admin_locationSuffix }}" \
          --parameters resourceSuffix="${{ env.admin_prjResourceSuffix }}" \
          --parameters aifactorySuffixRG="${{ env.admin_aifactorySuffixRG }}" \
          --parameters commonResourceSuffix="${{ env.admin_commonResourceSuffix }}" \
          --parameters projectServicePrincipleOID_SeedingKeyvaultName="${{ env.project_service_principal_OID_seeding_kv_name }}" \
          --parameters projectServicePrincipleAppID_SeedingKeyvaultName="${{ env.project_service_principal_AppID_seeding_kv_name }}" \
          --parameters projectServicePrincipleSecret_SeedingKeyvaultName="${{ env.project_service_principal_Secret_seeding_kv_name }}" \
          --parameters inputKeyvault="${{ env.admin_bicep_kv_fw }}" \
          --parameters inputKeyvaultResourcegroup="${{ env.admin_bicep_kv_fw_rg }}" \
          --parameters inputKeyvaultSubscription="${{ env.admin_bicep_input_keyvault_subscription }}" \
          --parameters IPwhiteList="${{ env.project_IP_whitelist }}"
        azcliversion: latest
    - name: 10_Remove ADO IP from keyvault FW whitelist
      uses: azure/cli@v2
      with:
        inlineScript: az keyvault network-rule remove --subscription ${{ env.admin_bicep_input_keyvault_subscription }} --resource-group ${{ env.admin_bicep_kv_fw_rg }} --name ${{ env.admin_bicep_kv_fw }} --ip-address ${{ env.admin_ip_fw }}
        azcliversion: latest
      if: always()