trigger:
  schedules:
  - cron: "0 2 * * *"  # Daily at 2 AM UTC
    displayName: Daily Cross-Charging Report
    branches:
      include:
      - main
    always: true

variables:
  - template: ../variables/variables.yaml

stages:
- stage: Dev_Cross_Charging
  displayName: Dev Cross-Charging Report
  variables:
    dev_test_prod: "dev"
    dev_test_prod_sub_id: "$(dev_sub_id)"
  jobs:
    - deployment: CrossChargingReport
      displayName: Generate Cross-Charging Report
      timeoutInMinutes: 60
      pool:
        vmImage: windows-2022
      environment: Dev  
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self
                submodules: recursive
                fetchDepth: 0
                displayName: 'Checkout with submodules'
              - template: ./jobs/job-cross-charging.yaml
                parameters:
                  serviceConnection: ${{ variables.dev_service_connection }}
                  serviceConnectionSeeding: ${{ variables.dev_seeding_kv_service_connection }}

- stage: Test_Cross_Charging
  displayName: Test Cross-Charging Report
  dependsOn: Dev_Cross_Charging
  condition: succeeded()
  variables:
    dev_test_prod: "test"
    dev_test_prod_sub_id: "$(test_sub_id)"
  jobs:
    - deployment: CrossChargingReport
      displayName: Generate Cross-Charging Report
      timeoutInMinutes: 60
      pool:
        vmImage: windows-2022
      environment: Test  
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self
                submodules: recursive
                fetchDepth: 0
                displayName: 'Checkout with submodules'
              - template: ./jobs/job-cross-charging.yaml
                parameters:
                  serviceConnection: ${{ variables.test_service_connection }}
                  serviceConnectionSeeding: ${{ variables.test_seeding_kv_service_connection }}

- stage: Prod_Cross_Charging
  displayName: Prod Cross-Charging Report
  dependsOn: Test_Cross_Charging
  condition: succeeded()
  variables:
    dev_test_prod: "prod"
    dev_test_prod_sub_id: "$(prod_sub_id)"
  jobs:
    - deployment: CrossChargingReport
      displayName: Generate Cross-Charging Report
      timeoutInMinutes: 60
      pool:
        vmImage: windows-2022
      environment: Prod  
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self
                submodules: recursive
                fetchDepth: 0
                displayName: 'Checkout with submodules'
              - template: ./jobs/job-cross-charging.yaml
                parameters:
                  serviceConnection: ${{ variables.prod_service_connection }}
                  serviceConnectionSeeding: ${{ variables.prod_seeding_kv_service_connection }}
