targetScope = 'resourceGroup'

@description('Validated deterministic role definitions generated by personas.policy. Each assignable scope is this RG.')
param roles array

resource customRoles 'Microsoft.Authorization/roleDefinitions@2022-04-01' = [for role in roles: {
  name: role.name
  properties: {
    roleName: role.properties.roleName
    description: role.properties.description
    type: 'CustomRole'
    assignableScopes: [resourceGroup().id]
    permissions: role.properties.permissions
  }
}]

output roleIds array = [for (role, index) in roles: customRoles[index].id]
