channels:
- anaconda
- conda-forge
- pytorch
dependencies:
- python=3.8.18
- pip:
  - mlflow==2.9.2
  - azureml-train-automl-runtime==1.54.0.post1
  - inference-schema
  - azureml-interpret==1.54.0
  - azureml-defaults==1.54.0
  - pytorch-transformers==1.0.0
  - spacy==2.1.8
  - https://aka.ms/automl-resources/packages/en_core_web_sm-2.1.0.tar.gz
- numpy==1.22.4
- pandas==1.3.5
- scikit-learn==1.0.2
- py-xgboost==1.3.3
- prophet==1.1.4
- holidays==0.29
- psutil==5.9.3
- pytorch==1.11.0
- cudatoolkit==9.0
name: project_environment
