name: verify-aifactory-dev
on: push
jobs:
  verify-infra:
    name: Verifies provisioning in DEV of an AI Factory common, and 2 project types ESML, ESGENAI
    environment:
      name: DEV
    runs-on: ubuntu-latest
    steps:
      - run: bicep --version
  verify-dataops-template:
    name: Verifies DATAOPS template in DEV for DataOps, ingestion from sources to ESML datalake
    environment:
      name: DEV
    runs-on: ubuntu-latest
    steps:
      - run: python --version
  verify-mlops-template:
    name: Verifies MLOPS template in DEV, for training, registering, deploying models, smoke-testing inference ep with monitoring
    environment:
      name: DEV
    runs-on: ubuntu-latest
    steps:
      - run: node --version
      - run: npm --version
  verify-genaiops-template:
    name: Verifies GenAIOps template in DEV, for RAG to Promptflow endpoint, smoke-testing inference with monitoring
    environment:
      name: DEV
    runs-on: ubuntu-latest
    steps:
      - run: python --version